version: '3.4'
services:
  fastapi:
    image: kaluiklui3011/test-1.0
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    ports:
      - 8000 
    environment:
